# Poem Example
import time
First_Line = input('What is the first line of your poem? ')
Second_Line = input('What is the second line of your poem? ')
Third_Line = input('What is the third line of your poem? ')
print("Here is your poem!")
time.sleep(1)
print('\n')
time.sleep(1)
print(First_Line)
print('\n')
time.sleep(1)
print(Second_Line)
print('\n')
time.sleep(1)
print(Third_Line)
print('\n')
time.sleep(1)
print('\n')
print('\n')
print('That is a nice poem.')
